name: ESLint

on:
  push:
    branches: ["master"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["master"]

jobs:
  Check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      packages: write

    steps:
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: bun install

      - name: Test
        run: bun test

      - name: Build
        run: bun build

  Publish:
    name: Publish
    needs: Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@lv00'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
